TestTask/apps/notes/urls.py
from django.urls import path
from TestTask.apps.notes.views import categoryView, noteView

app_name = 'notes'

urlpatterns = [
    path('', categoryView.index, name='index'),
    path('add_category/', categoryView.add_category, name='add_category'),
    path('delete_category/<int:id>/', categoryView.delete_category, name='delete_category'),
    path('category/edit/', categoryView.edit_category, name='edit_category'),

    path('category/<int:category_id>/', noteView.list_notes, name='list_notes'),
    path('category/<int:category_id>/<int:notes_id>/', noteView.notes_detail, name='notes_detail'),
    path('category/<int:category_id>/add_note/', noteView.add_note, name='add_note'),
    path('category/<int:category_id>/<int:notes_id>/delete_note', noteView.delete_note, name='delete_note'),
    path('category/<int:category_id>/<int:notes_id>/edit_note', noteView.edit_note, name='edit_name'),

    path('encoding/', noteView.encoding, name='encoding'),
    path('decoding/', noteView.decoding, name='decoding'),

]

TestTask/apps/register/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as loginView

app_name = 'register'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('', loginView.LoginView.as_view(), name='login'),
    path('logout/', loginView.LogoutView.as_view(), name='logout')

]

TestTask/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('notes.urls')),
    path('login/', include('register.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

TestTask/apps/notes/models.py
from django.db import models
from django.contrib.auth.models import User


class СategoryNote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="notes", null=True)
    category_title = models.CharField('Название заметки', max_length=200)

    def __str__(self):
        return self.category_title


class Note(models.Model):
    category = models.ForeignKey(СategoryNote, on_delete=models.CASCADE)
    name_note = models.CharField('Название заметки', max_length=200)
    text_note = models.BinaryField('Текст заметки')
    key = models.BinaryField('Ключ шифрования')

    def __str__(self):
        return self.name_note

TestTask/apps/register/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "password1", "password2"]

TestTask/apps/notes/views/categoryView.py
from django.http import Http404, HttpResponseRedirect
from django.contrib import auth
from django.shortcuts import render, redirect
from TestTask.apps.notes.models import СategoryNote, Note


def index(request):
    if request.user.is_authenticated:
        list_category = СategoryNote.objects.filter(user=request.user)
        return render(request, "notes/category.html", {"title_block": "Категории", "list": list_category})
    else:
        return redirect("/login/")


def add_category(request):
    if request.user.is_authenticated:
        if request.method == "POST":
            add = СategoryNote(id=None, user=auth.get_user(request), category_title=request.POST['name'])
            add.save()
        list_category = СategoryNote.objects.all()
        return redirect("/")
    else:
        return redirect("/")


def edit_category(request):
    if request.user.is_authenticated:
        try:
            category = СategoryNote.objects.get(id=request.POST['id_category'])
            category.category_title = request.POST['name_category']
            category.save()
            return HttpResponseRedirect("/")
        except:
            return HttpResponseRedirect("/")
    else:
        return redirect("/")


def delete_category(request, id):
    if request.user.is_authenticated:
        try:
            category = СategoryNote.objects.get(id=id)
            category.delete()
            return HttpResponseRedirect("/")
        except:
            raise Http404('Категория не найдена')
    else:
        return redirect("/")

TestTask/apps/notes/views/noteView.py
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.contrib import auth
from django.shortcuts import render, redirect
from TestTask.apps.notes.models import СategoryNote, Note
import hashlib
from Crypto.Cipher import Salsa20
import json

def encoding(plaintext, key):
    secret = hashlib.sha256(key.encode()).digest()
    cipher = Salsa20.new(key=secret)
    msg = cipher.nonce + cipher.encrypt(plaintext.encode())
    return (msg)


def decoding(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            data = json.loads(request.body.decode("utf-8"))
            msg_key = Note.objects.get(id=data['idNote']).key
            msg = Note.objects.get(id=data['idNote']).text_note
            key = data['keyNote']
            secret = hashlib.sha256(key.encode()).digest()
            msg_nonce = msg_key[:8]
            ciphertext = msg_key[8:]
            cipher = Salsa20.new(key=secret, nonce=msg_nonce)
            plaintext = cipher.decrypt(ciphertext)
            try:
                password = plaintext.decode()
                if password == key:
                    msg_nonce = msg[:8]
                    ciphertext = msg[8:]
                    cipher = Salsa20.new(key=secret, nonce=msg_nonce)
                    plaintext = cipher.decrypt(ciphertext)
                    return HttpResponse(plaintext)
                else:
                    return HttpResponse('None')
            except:
                return HttpResponse('None')

def list_notes(request, category_id):
    if request.user.is_authenticated:
        category = СategoryNote.objects.get(id=category_id)
        if request.user == category.user:
            list_notes = category.note_set.all()
            return render(request, "notes/notes.html", {"list": list_notes, "id_category": category_id})
        else:
            raise Http404("В доступе отказано")

    else:
        return redirect("/login/")


def notes_detail(request, category_id, notes_id):
    if category_id:
        a = Note.objects.get(id=notes_id)
        a.text_note = a.text_note.tobytes()
    return render(request, "notes/notes_detail.html", {"result": a, "flag_add": False})


def add_note(request, category_id):
    if request.user.is_authenticated:
        if request.method == "POST" and bool(category_id):
            categoryAdd = СategoryNote.objects.get(id=category_id)
            add = Note(category=categoryAdd, name_note=request.POST['name_note'],
                       text_note=encoding(request.POST['text_note'], request.POST['password']),
                       key=encoding(request.POST['password'], request.POST['password']))
            add.save()
            return redirect("/category/" + str(category_id))
        else:
            return render(request, "notes/notes_detail.html", {"result": None, "flag_add": True})
    else:
        return redirect("/")


def delete_note(request, category_id, notes_id):
    if request.user.is_authenticated:
        try:
            note = Note.objects.get(id=notes_id)
            note.delete()
            return redirect("/category/" + str(category_id))
        except:
            raise Http404('Заметка не найдена')
    else:
        return redirect("/")


def edit_note(request, category_id, notes_id):
    if request.user.is_authenticated:
        if request.method == "POST" and bool(category_id) and bool(notes_id):
            note = Note.objects.get(id=notes_id)
            note.name_note = request.POST['name_note']
            note.text_note = encoding(request.POST['text_note'], request.POST['password'])
            note.key = encoding(request.POST['password'], request.POST['password'])
            note.save()
            return redirect("/category/" + str(category_id))
    else:
        return redirect("/")

TestTask/apps/register/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm
from django.contrib.auth import login, authenticate


def register(response):
    if response.method == "POST":
        form = RegisterForm(response.POST)
        if form.is_valid():
            form.save()
        return redirect("/")
    else:
        form = RegisterForm()
    return render(response, "registration/register.html", {"form":form})

TestTask/apps/notes/templates/notes/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Заметки</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-dark bg-primary ">
        <span class="navbar-brand mb-2 h1">Заметки</span>

        <a href="{% url 'register:logout' %}" class="btn btn-outline-dark my-2 my-sm-0 float-right" type="submit">Выход</a>
    </nav>
    <br>
    <div  class="container">
        <div  class="row justify-content-start">
            <div  class="col-5" >
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>
    {% include 'notes/notes/modals/modal.html' %}



</body>
</html>

TestTask/apps/notes/templates/notes/category.html
{% extends 'notes/base.html' %}
{% load static %}


{% block content %}
    <div class="add-row">
        <div class="list-group-center col">
            <form action="{% url 'notes:add_category' %}" method="POST" class="form-inline">
                {% csrf_token %}
                <input class="form-control mr-sm-2" name="name" type="search" required placeholder="Название категории" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Добавить</button>
            </form>
        </div>
    </div>
    <br>
    <ul class="list-group-center col">
        <li class="list-group-item active h5">{{ title_block }}</li>
        {% if list %}
            {%  for a in list %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <a href="{% url 'notes:list_notes' a.id %}" class="list-group ">{{ a.category_title }}</a>
                    <div class="btn-group" role="group">
                        <a  data-toggle="modal" data-target="#edit_category" data-id="{{ a.id }}" data-name="{{ a.category_title }}" class="list-group"><img src="{% static "notes/img/rename_icon.png" %}" alt="..." class="img-circle" width="50%"></a>
                        <a href="{% url 'notes:delete_category' a.id %}" class="list-group"><img src="{% static "notes/img/delete_icon.png" %}" alt="..." class="img-circle" width="50%"></a>
                    </div>
                </li>
            {% endfor %}
        {% else %}
            <li class="list-group-item">Категории отсутствуют</li>
        {% endif %}
    </ul>





{% endblock %}

TestTask/apps/notes/templates/notes/notes.html
{% extends 'notes/base.html' %}
{% load static %}

{% block content %}

    <div class="add-row">
        <div class="list-group-center col">
            <div class="row justify-content-around">
                <a href="{% url 'notes:index' %}" class="btn btn-outline-success my-2 my-sm-0" type="submit">Категории</a>
                <a href="{% url 'notes:add_note' id_category %}" class="btn btn-outline-success my-2 my-sm-0" type="submit">Добавить</a>

            </div>
        </div>
    </div>
    <br>
    <div class="list-group-center col">
        <li class="list-group-item active h5">Заметки</li>
        {% if list %}
            {%  for a in list %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <a href="{% url 'notes:notes_detail' a.category.id a.id %}" class="list-group ">{{ a.name_note }}</a>
                    <div class="btn-group" role="group" aria-label="">
                        <a href="{% url 'notes:delete_note' a.category.id a.id %}" class="list-group"><img src="{% static "notes/img/delete_icon.png" %}" alt="..." class="img-circle" width="50%"></a>
                    </div>
                </li>
            {% endfor %}
        {% else %}
            <p class="list-group-item list-group-item-action">Заметки отсутствуют Alll</p>
        {% endif %}
        <br>

    </div>


{% endblock %}

TestTask/apps/notes/templates/notes/notes/modals/modal.html
<div class="modal fade" id="edit_category" tabindex="-1" role="dialog" aria-labelledby="edit_category" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="edit_category">Редактирование категории</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="{% url 'notes:edit_category' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="recipient-name" class="col-form-label">Название категории:</label>
                        <input type="text" class="form-control" id="name_category" name="name_category" required value="">
                        <input name="id_category" type="hidden" id="id_category" value="">
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                        <button type="submit" class="btn btn-primary">Сохраниеть</button>
                    </div>
                </form>
            </div>

        </div>
    </div>
</div>
<script>
    $('#edit_category').on('show.bs.modal', function (event) {
        var button = $(event.relatedTarget)
        var id = button.data('id')
        var name = button.data('name')
        var modal = $(this)
        document.getElementById('name_category').setAttribute("value", name)
        document.getElementById('id_category').setAttribute("value", id)
    })
</script>

TestTask/apps/notes/templates/notes/notes_detail.html
{% extends 'notes/base.html' %}

{% block content %}

    <div class="card">
        <div class="card-body">
            {% if flag_add == False %}

                    <div  class="col">
                        <form action="{% url 'notes:edit_name' result.category.id result.id %}" method="post" name="data_content" id="data">
                            {% csrf_token %}
                            <div class="form-group mb-3>
                                <label for="exampleFormControlInput1">Название</label>
                                <input name="name_note" type="text" value="{{ result.name_note }}" class="form-control mb-1" id="exampleFormControlInput1" required placeholder="">
                                <label for="exampleFormControlTextarea1">Текст</label>
                                <textarea id="text_note" name="text_note" class="form-control" id="exampleFormControlTextarea1" required rows="3" >{{ result.text_note }}</textarea>
                            </div>
                        </form>
                            <div class="row">
                                    <input form="data" name="password" id="pass_note" type="password" class="form-control col-7 ml-3" id="password" required placeholder="Пароль">
                                    <button id="dencoding" class="btn btn-primary col ml-1 mr-2">Расшифровать</button>
                            </div>

                            <div class="row justify-content-center">
                                <button disabled form="data" type="submit" id="buttonSave" class="btn btn-primary col-4 mt-3 mb-2">Сохранить</button>
                            </div>
                    </div>

                {% else %}
                        <h5 class="card-title ml-3">Создание заметки</h5>
                        <hr align="center" color="gray" />
                        <div  class="col">
                            <form action="" method="post" name="data_content">
                                {% csrf_token %}
                                <div class="form-group >
                                    <label for="exampleFormControlInput1">Название</label>
                                    <input type="text" value="" id="name_note" name="name_note" class="form-control" required placeholder="">
                                    <label for="exampleFormControlTextarea1">Текст</label>
                                    <textarea class="form-control" id="text_note" name="text_note"rows="3" required></textarea>
                                </div>
                                <div class="row">
                                    <input type="password" id="pass_note" class="form-control col-7 ml-3" name="password" required placeholder="Пароль">
                                    <button type="submit" id="buttonCreat" class="btn btn-primary col ml-1 mr-3">Сохранить</button>
                                </div>
                            </form>
                        </div>
            {% endif %}
        </div>
    </div>

    <script>
        $("#dencoding").click(function() {
            encoding()
        });

        function encoding() {
            const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
            let textNote = document.getElementById("text_note");
            let keyNote = document.getElementById("pass_note").value;
            let encodingNote = {
                idNote: {{ result.id }},
                keyNote: keyNote
            };
            fetch('{% url 'notes:decoding' %}',{
                mode: 'same-origin',
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json;charset=utf-8',
                    'X-CSRFToken': csrftoken
                },
                body: JSON.stringify(encodingNote)
                }).then(function (response) {
                    response.text().then(function (data) {
                        if (data == 'None'){
                            alert('Пароль неверный')
                        }else{
                            textNote.value = data
                            document.getElementById("buttonSave").disabled=false
                            document.getElementById("dencoding").disabled=true
                        }

                })
            });

        }



    </script>


{% endblock %}